name: "oidc auth"
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  id-token: write
jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: us-east-1
      - name: whoami
        run: aws sts get-caller-identity